### ISSUE TITLE
Can we provide more versions for more recent releases of elasticsearch?

### ISSUE THREAD

**Issue by drocsid** [pires/docker-elasticsearch#11]
3 more versions of elasticsearch were released December 17th:

Elasticsearch 2.1.1
December 17, 2015

Elasticsearch 2.0.2
December 17, 2015

Elasticsearch 1.7.4
December 17, 2015

Do you plan on creating branches to support the different elasticsearch releases? Since you are storing the docker images on a registry, you should be able to provide different images for each release.

**Comment by drocsid** [comment]
Just another curiosity, why do you set your environment inside the run.sh script, instead of using the ENV  instruction inside the dockerfile? Doesn't this make your container less portable, and sort of odd?

**Comment by drocsid** [comment]
Elasticsearch 2.2 coming soon.

**Comment by pires** [comment]
I am upgrading to 2.1.1 now.

I am not planning in _supporting_ multiple versions but am open to review PRs.

**Comment by pires** [comment]
Actually, thanks to you, I'm giving it a second thought. https://github.com/pires/docker-elasticsearch/tree/1.7.x
