### ISSUE TITLE
Link containers - es-master/es-client and es-data?

### ISSUE THREAD

**Issue by DivyaYash** [pires/docker-elasticsearch#13]
@pires - Am a newbie in the docker world, appreciate your work and thanks in advance.
I have one VM which has docker installed, now am trying to setup three individual containers for elasticsearch, following your guide, - one each for master, client and data. I used the below docker cmds to run them, in the same order..When I try to test the cluster status, I get an error saying, 

**"Master Not Discovered Error"**
*[2016-01-06 09:09:31,393][WARN ][discovery.zen.ping.unicast] [Wysper] failed to send ping to   [{#zen_unicast_6#}{::1}{[::1]:9300}]
SendRequestTransportException[[][[::1]:9300][internal:discovery/zen/unicast]]; nested: NodeNotConnectedException[[][[::1]:9300] Node not connected];*

I believe it is an issue with the IP it defaults to, when the port 9300 is opened and other containers cannot talk to master on 9300..
Should I be linking the containers to get it working? Or is there something technically wrong in what am trying? Looking forward for your guidance here..

*docker run --name es-master --detach --privileged -p 9300:9300 --volume /opt/es/data:/data -e CLUSTER_NAME=esclus-test -e NODE_DATA=false -e HTTP_ENABLE=false quay.io/pires/docker-elasticsearch:2.1.0*

*docker run --name es-client --detach --privileged -p 9200:9200 --volume /opt/es/data:/data -e CLUSTER_NAME=esclus-dpev304 -e NODE_MASTER=false -e NODE_DATA=false quay.io/pires/docker-elasticsearch:2.1.0*

*docker run --name es-data --detach --privileged --volume /opt/es/data:/data -e CLUSTER_NAME=esclus-dpev304 -e NODE_MASTER=false -e HTTP_ENABLE=false quay.io/pires/docker-elasticsearch:2.1.0*

**Comment by pires** [comment]
Yes, you should look for Docker networking to _link_ your containers.

For clustering to work on the same host, you need to expose ports TCP 9300 at least, but obviously expose as different nodes. I'm not sure multicast will work here.

Also, you're abusing `--volume /opt/es/data:/data`. Each container will use the same path :-s

**Comment by DivyaYash** [comment]
Ok, thank u, I will check on these lines..
Have one query plz, the 9300 port is associated with the master component and 9200 is associated with client right? Task at hand is, I need to figure out how the data container can realize that master container is already present and listening on port 9300 - true?

**Comment by pires** [comment]
`9300` is used for intra-cluster communication, `9200` is used by clients that use the HTTP API.

**Comment by DivyaYash** [comment]
So, port 9300 and 9200 will be exposed as part of your image for all the components (master/client/data)
But from the docker run, for which component should I map port to host machine? 
Also, which container needs to be linked with which? client and data needs to be linked with master? 
Please bear with me, Still going through ES documents to understand the concepts, meanwhile seeking your advice.. Thank u for all your help.
