### ISSUE TITLE
Does discovery mode avoid split brain syndrome?

### ISSUE THREAD

**Issue by vichargrave** [pires/docker-elasticsearch#18]
Does the Kubernetes discovery mode of the fabric8 discovery plugin avoid split brain syndrome if you have multiple master nodes in your cluster?  If not, then I'm wondering if the ```discovery.zen.minimum_master_node``` configuration field from a regular _elasticsearch.yml_ file should be exposed in the Kubernetes Docker container _elasticsearch.yml_ file.

**Comment by pires** [comment]
That's a very important setting indeed.

**Comment by vichargrave** [comment]
I take it by your answer that the discovery plugin does not take care of this and that this field should be exposed.  If so, then I can add it and do a pull request.

**Comment by pires** [comment]
I was already expecting that.

**Comment by vichargrave** [comment]
OK I'll put the change in the docker-elasticsearch-kubernetes repo.  I'm also going to add back the runs.sh script that was deleted from the 2.3.5 tag of that repo.  Not sure why it was deleted.

**Comment by pires** [comment]
Because it is inherited from this repo. Put it here, please.

**Comment by vichargrave** [comment]
ok will do.  ignore my comment in that repo.

**Comment by pires** [comment]
The solution here is specific to Elasticsearch, so `discovery.zen.minimum_master_nodes` should be set in this repo.
