### ISSUE TITLE
elasticsearch-plugin: Text file busy

### ISSUE THREAD

**Issue by devth** [pires/docker-elasticsearch#33]
FYI I'm hitting this error ocassionally when bringing up my pods on GKE:

```bash
/run.sh: line 28: /elasticsearch/bin/elasticsearch-plugin: Text file busy
/run.sh: line 28: /elasticsearch/bin/elasticsearch-plugin: Text file busy
```

From reading [this thread](https://github.com/docker/docker/issues/9547) possible workarounds might be running `sync` or `sleep 1` after `chown`ing.

Related to #31 

Happy to PR and test fixes pending your (or anyone else's) thoughts on this issue.

**Comment by pires** [comment]
Happy to review any PRs that fix this but right now I'm unable to verify it.
