### ISSUE TITLE
[Question] ENV NUMBER_OF_SHARDS and ENV NUMBER_OF_REPLICAS

### ISSUE THREAD

**Issue by acscloud** [pires/docker-elasticsearch#35]
Hi

env NUMBER_OF_SHARDS and ENV NUMBER_OF_REPLICAS are defined in Dockerfile, are they available? I'm asking because I didn't see them in elasticsearch.yml. Thanks.

**Comment by pires** [comment]
Good catch. [I removed it](https://github.com/pires/docker-elasticsearch/commit/6b4ebd99248fc1b2a3c9fb13290b33de84355b58#diff-5041c7795341409bacea5941f88a69f4) as it doesn't seem to be available any more, right? Feel free to open a PR to remove that from the `Dockerfile`.
