### ISSUE TITLE
setting REPO_LOCATIONS environment variable does not work

### ISSUE THREAD

**Issue by waterdudu** [pires/docker-elasticsearch#58]
Hi pires,
I noticed `REPO_LOCATIONS` appears only [in the doc](https://github.com/pires/docker-elasticsearch#environment-variables), I cannot find any usage in `run.sh` or config file. Could you please explain how to set this variable properly when running this image?

Thanks

**Comment by pires** [comment]
On it!

**Comment by pires** [comment]
Fixed by https://github.com/pires/docker-elasticsearch/commit/5150b9327a44ec7c113ccb540a0768c905f33d14
