### ISSUE TITLE
Support for additional ES command line args

### ISSUE THREAD

**Issue by mbert** [pires/docker-elasticsearch#59]
I am trying to implement the "hot/warm" architecture proposed in the ES blog post [“Hot-Warm” Architecture in Elasticsearch 5.x](https://www.elastic.co/blog/hot-warm-architecture-in-elasticsearch-5-x) in Kubernetes based on [pires/kubernetes-elasticsearch-cluster](https://github.com/pires/kubernetes-elasticsearch-cluster). One obstacle I have been running into was that Elasticsearch nodes need the attribute `node.attr.box_type=hot` to be set. This does not work with Java System Properties (hence the `ES_JAVA_OPTS` do not help here), it needs to be passed to `elasticsearch` as command line argument: `-Enode.attr.box_type=hot`.

Since from version 5, ES [no longer supports configuration via System Properties](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/breaking_50_settings_changes.html), I think that a generic mechanism for passing command line args to `elasticsearch` in `run.sh` might come in handy for this but also different, not yet thought-of scenarios. I'm filing a PR for this now for your kind consideration.

**Comment by pires** [comment]
Closed by #60

**Comment by pires** [comment]
Done.
