### ISSUE TITLE
Incorrect repo_location documentation

### ISSUE THREAD

**Issue by Sykomaniac** [pires/docker-elasticsearch#68]
When reading through the documentation around adding a back-up location to the elastic config the documentation reads:

> Then, set the REPO_LOCATIONS environment variable to ["/backup"] and create a backup repository

However, when REPO_LOCATIONS is substituted to the environment variable value it is already wrapped within an array. Therefore, the REPO_LOCATIONS env variable should just be initialized as a string e.g. `/backup`.

**Comment by pires** [comment]
Thank you for reporting. I'm happy to review a PR that addresses this!

**Comment by Sykomaniac** [comment]
@pires No problem PR sent - I tend to be overly verbose so hopefully my edits are suitable :+1:

**Comment by pires** [comment]
I love verbosity when it makes documentation clearer.
