### ISSUE TITLE
ElasticSearch Data takes a very long time to chown existing data folder

### ISSUE THREAD

**Issue by nick-pap** [pires/docker-elasticsearch#70]
The current startup script uses chown -R to set the elasticsearch:elasticsearch owner of the data folder.

However, this can get VERY slow when the folder already contains indexes.

https://www.unixlore.net/articles/speeding-up-bulk-file-operations.html provides an alternative logic:

find . -type f -print0 | xargs -0 chown elasticsearch:elasticsearch

**Comment by pires** [comment]
Fixed in https://github.com/pires/docker-elasticsearch/releases/tag/6.4.0
