### ISSUE TITLE
Installing SearchGuard plugin

### ISSUE THREAD

**Issue by ploef** [pires/docker-elasticsearch#72]
Hi,

I'm trying to install the SearchGuard plugin. Unfortunately I get an error message during the installation of the plugin telling me it can not find the folder "x-pack-ml". This seems logical to me because x-pack-ml is not enabled but...does this mean I cannot use this plugin using this (alpine) base image?

**Comment by pires** [comment]
Seems like it.

**Comment by ploef** [comment]
ok thanks for clearing that
